name: attempt to run

on: push

jobs:
    runnerino:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
            - name: install python ***3.12***
              uses: actions/setup-python@v6
              with:
                  python-version: 3.12
            - name: run!!!!!!
              run: |
                  attemptChallenges() {
                      git diff-tree --no-commit-id --name-only -r HEAD
                      git diff-tree --no-commit-id --name-only -r HEAD | sed '/\/\//!q1'
                      canRun=$?
                      if [ $canRun -eq 0 ]; then
                          dirs=$(find . -maxdepth 1 -type d -name 'uzduotis*' | sed 's|^\./||' | sort -t s -k 2,2n)
                          for d in $dirs; do
                              echo "$d:" | sed "s/^uzduotis/Užduotis #/"
                              (cd "$d" && python main.py ; true)
                          done
                          return
                      fi
                      echo "Žiurėkite praeitą commit jei norite output."
                  }
                  attemptChallenges