name: attempt to run

on: push

jobs:
    runnerino:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: install python ***3.12***
              uses: actions/setup-python@v6
              with:
                  python-version: 3.12
            - name: run!!!!!!
              run: |
                  attemptChallenges() {
                      if git diff-tree --no-commit-id --name-only -r HEAD | grep -vq '/'; then
                          echo "Žiūrėkite praeitą commit jei norite output."
                          return
                      fi
                      dirs=$(find . -maxdepth 1 -type d -name 'uzduotis*' | sed 's|^\./||' | sort -t s -k 2,2n)
                      for d in $dirs; do
                          echo "$d:" | sed "s/^uzduotis/Užduotis #/"
                          (cd "$d" && python main.py || true)
                      done
                      return
                  }
                  attemptChallenges